/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as PortalRouteImport } from './routes/_portal'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as JoinRouteImport } from './routes/join'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated.clients'
import { Route as AuthenticatedCommandCentreRouteImport } from './routes/_authenticated.command-centre'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated.dashboard'
import { Route as AuthenticatedExclientsRouteImport } from './routes/_authenticated.exclients'
import { Route as AuthenticatedLinksRouteImport } from './routes/_authenticated.links'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated.onboarding'
import { Route as AuthenticatedRenewalsRouteImport } from './routes/_authenticated.renewals'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated.settings'
import { Route as AuthenticatedTodosRouteImport } from './routes/_authenticated.todos'
import { Route as AuthenticatedUpsellsRouteImport } from './routes/_authenticated.upsells'
import { Route as PortalPortalRouteImport } from './routes/_portal.portal'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated.clients.index'
import { Route as AuthenticatedClientsClientIdRouteImport } from './routes/_authenticated.clients.$clientId'
import { Route as ApiPublicOnboardingHookRouteImport } from './routes/api/public/onboarding-hook'
import { Route as ApiPublicSheetSyncRouteImport } from './routes/api/public/sheet-sync'
import { Route as AuthenticatedClientsClientIdIndexRouteImport } from './routes/_authenticated.clients.$clientId.index'
import { Route as AuthenticatedClientsClientIdPortalRouteImport } from './routes/_authenticated.clients.$clientId.portal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCommandCentreRoute =
  AuthenticatedCommandCentreRouteImport.update({
    id: '/command-centre',
    path: '/command-centre',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedExclientsRoute = AuthenticatedExclientsRouteImport.update({
  id: '/exclients',
  path: '/exclients',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLinksRoute = AuthenticatedLinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRenewalsRoute = AuthenticatedRenewalsRouteImport.update({
  id: '/renewals',
  path: '/renewals',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTodosRoute = AuthenticatedTodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUpsellsRoute = AuthenticatedUpsellsRouteImport.update({
  id: '/upsells',
  path: '/upsells',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PortalPortalRoute = PortalPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => PortalRoute,
} as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientsRoute,
  } as any)
const AuthenticatedClientsClientIdRoute =
  AuthenticatedClientsClientIdRouteImport.update({
    id: '/$clientId',
    path: '/$clientId',
    getParentRoute: () => AuthenticatedClientsRoute,
  } as any)
const ApiPublicOnboardingHookRoute = ApiPublicOnboardingHookRouteImport.update({
  id: '/api/public/onboarding-hook',
  path: '/api/public/onboarding-hook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSheetSyncRoute = ApiPublicSheetSyncRouteImport.update({
  id: '/api/public/sheet-sync',
  path: '/api/public/sheet-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientsClientIdIndexRoute =
  AuthenticatedClientsClientIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientsClientIdRoute,
  } as any)
const AuthenticatedClientsClientIdPortalRoute =
  AuthenticatedClientsClientIdPortalRouteImport.update({
    id: '/portal',
    path: '/portal',
    getParentRoute: () => AuthenticatedClientsClientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
  '/reset-password': typeof ResetPasswordRoute
  '/clients': typeof AuthenticatedClientsRouteWithChildren
  '/command-centre': typeof AuthenticatedCommandCentreRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exclients': typeof AuthenticatedExclientsRoute
  '/links': typeof AuthenticatedLinksRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/renewals': typeof AuthenticatedRenewalsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/todos': typeof AuthenticatedTodosRoute
  '/upsells': typeof AuthenticatedUpsellsRoute
  '/portal': typeof PortalPortalRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdRouteWithChildren
  '/api/public/onboarding-hook': typeof ApiPublicOnboardingHookRoute
  '/api/public/sheet-sync': typeof ApiPublicSheetSyncRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
  '/clients/$clientId/portal': typeof AuthenticatedClientsClientIdPortalRoute
  '/clients/$clientId/': typeof AuthenticatedClientsClientIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
  '/reset-password': typeof ResetPasswordRoute
  '/command-centre': typeof AuthenticatedCommandCentreRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exclients': typeof AuthenticatedExclientsRoute
  '/links': typeof AuthenticatedLinksRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/renewals': typeof AuthenticatedRenewalsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/todos': typeof AuthenticatedTodosRoute
  '/upsells': typeof AuthenticatedUpsellsRoute
  '/portal': typeof PortalPortalRoute
  '/api/public/onboarding-hook': typeof ApiPublicOnboardingHookRoute
  '/api/public/sheet-sync': typeof ApiPublicSheetSyncRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
  '/clients/$clientId/portal': typeof AuthenticatedClientsClientIdPortalRoute
  '/clients/$clientId': typeof AuthenticatedClientsClientIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_portal': typeof PortalRouteWithChildren
  '/auth': typeof AuthRoute
  '/join': typeof JoinRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRouteWithChildren
  '/_authenticated/command-centre': typeof AuthenticatedCommandCentreRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/exclients': typeof AuthenticatedExclientsRoute
  '/_authenticated/links': typeof AuthenticatedLinksRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/renewals': typeof AuthenticatedRenewalsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/todos': typeof AuthenticatedTodosRoute
  '/_authenticated/upsells': typeof AuthenticatedUpsellsRoute
  '/_portal/portal': typeof PortalPortalRoute
  '/_authenticated/clients/$clientId': typeof AuthenticatedClientsClientIdRouteWithChildren
  '/api/public/onboarding-hook': typeof ApiPublicOnboardingHookRoute
  '/api/public/sheet-sync': typeof ApiPublicSheetSyncRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
  '/_authenticated/clients/$clientId/portal': typeof AuthenticatedClientsClientIdPortalRoute
  '/_authenticated/clients/$clientId/': typeof AuthenticatedClientsClientIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/join'
    | '/reset-password'
    | '/clients'
    | '/command-centre'
    | '/dashboard'
    | '/exclients'
    | '/links'
    | '/onboarding'
    | '/renewals'
    | '/settings'
    | '/todos'
    | '/upsells'
    | '/portal'
    | '/clients/$clientId'
    | '/api/public/onboarding-hook'
    | '/api/public/sheet-sync'
    | '/clients/'
    | '/clients/$clientId/portal'
    | '/clients/$clientId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/join'
    | '/reset-password'
    | '/command-centre'
    | '/dashboard'
    | '/exclients'
    | '/links'
    | '/onboarding'
    | '/renewals'
    | '/settings'
    | '/todos'
    | '/upsells'
    | '/portal'
    | '/api/public/onboarding-hook'
    | '/api/public/sheet-sync'
    | '/clients'
    | '/clients/$clientId/portal'
    | '/clients/$clientId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_portal'
    | '/auth'
    | '/join'
    | '/reset-password'
    | '/_authenticated/clients'
    | '/_authenticated/command-centre'
    | '/_authenticated/dashboard'
    | '/_authenticated/exclients'
    | '/_authenticated/links'
    | '/_authenticated/onboarding'
    | '/_authenticated/renewals'
    | '/_authenticated/settings'
    | '/_authenticated/todos'
    | '/_authenticated/upsells'
    | '/_portal/portal'
    | '/_authenticated/clients/$clientId'
    | '/api/public/onboarding-hook'
    | '/api/public/sheet-sync'
    | '/_authenticated/clients/'
    | '/_authenticated/clients/$clientId/portal'
    | '/_authenticated/clients/$clientId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
  AuthRoute: typeof AuthRoute
  JoinRoute: typeof JoinRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicOnboardingHookRoute: typeof ApiPublicOnboardingHookRoute
  ApiPublicSheetSyncRoute: typeof ApiPublicSheetSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/command-centre': {
      id: '/_authenticated/command-centre'
      path: '/command-centre'
      fullPath: '/command-centre'
      preLoaderRoute: typeof AuthenticatedCommandCentreRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exclients': {
      id: '/_authenticated/exclients'
      path: '/exclients'
      fullPath: '/exclients'
      preLoaderRoute: typeof AuthenticatedExclientsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/links': {
      id: '/_authenticated/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof AuthenticatedLinksRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/renewals': {
      id: '/_authenticated/renewals'
      path: '/renewals'
      fullPath: '/renewals'
      preLoaderRoute: typeof AuthenticatedRenewalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/todos': {
      id: '/_authenticated/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof AuthenticatedTodosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/upsells': {
      id: '/_authenticated/upsells'
      path: '/upsells'
      fullPath: '/upsells'
      preLoaderRoute: typeof AuthenticatedUpsellsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_portal/portal': {
      id: '/_portal/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalPortalRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/_authenticated/clients/$clientId': {
      id: '/_authenticated/clients/$clientId'
      path: '/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedClientsRoute
    }
    '/api/public/onboarding-hook': {
      id: '/api/public/onboarding-hook'
      path: '/api/public/onboarding-hook'
      fullPath: '/api/public/onboarding-hook'
      preLoaderRoute: typeof ApiPublicOnboardingHookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sheet-sync': {
      id: '/api/public/sheet-sync'
      path: '/api/public/sheet-sync'
      fullPath: '/api/public/sheet-sync'
      preLoaderRoute: typeof ApiPublicSheetSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clients/$clientId/': {
      id: '/_authenticated/clients/$clientId/'
      path: '/'
      fullPath: '/clients/$clientId/'
      preLoaderRoute: typeof AuthenticatedClientsClientIdIndexRouteImport
      parentRoute: typeof AuthenticatedClientsClientIdRoute
    }
    '/_authenticated/clients/$clientId/portal': {
      id: '/_authenticated/clients/$clientId/portal'
      path: '/portal'
      fullPath: '/clients/$clientId/portal'
      preLoaderRoute: typeof AuthenticatedClientsClientIdPortalRouteImport
      parentRoute: typeof AuthenticatedClientsClientIdRoute
    }
  }
}

interface AuthenticatedClientsClientIdRouteChildren {
  AuthenticatedClientsClientIdPortalRoute: typeof AuthenticatedClientsClientIdPortalRoute
  AuthenticatedClientsClientIdIndexRoute: typeof AuthenticatedClientsClientIdIndexRoute
}

const AuthenticatedClientsClientIdRouteChildren: AuthenticatedClientsClientIdRouteChildren =
  {
    AuthenticatedClientsClientIdPortalRoute:
      AuthenticatedClientsClientIdPortalRoute,
    AuthenticatedClientsClientIdIndexRoute:
      AuthenticatedClientsClientIdIndexRoute,
  }

const AuthenticatedClientsClientIdRouteWithChildren =
  AuthenticatedClientsClientIdRoute._addFileChildren(
    AuthenticatedClientsClientIdRouteChildren,
  )

interface AuthenticatedClientsRouteChildren {
  AuthenticatedClientsClientIdRoute: typeof AuthenticatedClientsClientIdRouteWithChildren
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
}

const AuthenticatedClientsRouteChildren: AuthenticatedClientsRouteChildren = {
  AuthenticatedClientsClientIdRoute:
    AuthenticatedClientsClientIdRouteWithChildren,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
}

const AuthenticatedClientsRouteWithChildren =
  AuthenticatedClientsRoute._addFileChildren(AuthenticatedClientsRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRouteWithChildren
  AuthenticatedCommandCentreRoute: typeof AuthenticatedCommandCentreRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExclientsRoute: typeof AuthenticatedExclientsRoute
  AuthenticatedLinksRoute: typeof AuthenticatedLinksRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedRenewalsRoute: typeof AuthenticatedRenewalsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTodosRoute: typeof AuthenticatedTodosRoute
  AuthenticatedUpsellsRoute: typeof AuthenticatedUpsellsRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedClientsRoute: AuthenticatedClientsRouteWithChildren,
  AuthenticatedCommandCentreRoute: AuthenticatedCommandCentreRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExclientsRoute: AuthenticatedExclientsRoute,
  AuthenticatedLinksRoute: AuthenticatedLinksRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedRenewalsRoute: AuthenticatedRenewalsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTodosRoute: AuthenticatedTodosRoute,
  AuthenticatedUpsellsRoute: AuthenticatedUpsellsRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PortalRouteChildren {
  PortalPortalRoute: typeof PortalPortalRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalPortalRoute: PortalPortalRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
  AuthRoute: AuthRoute,
  JoinRoute: JoinRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicOnboardingHookRoute: ApiPublicOnboardingHookRoute,
  ApiPublicSheetSyncRoute: ApiPublicSheetSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
